# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: HomePage}
          - {label: Slug, name: slug, widget: hidden, default: ''}
          - {label: Title, name: title, widget: string, required: false}
          - {label: Test, name: test, widget: string, required: false}
      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Template, name: template, widget: hidden, default: AboutPage}
          - {label: Slug, name: slug, widget: hidden, default: 'about'}
          - {label: Title, name: title, widget: string, required: false}

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
